// <auto-generated />
using CounterAPI.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CounterAPI.Migrations
{
    [DbContext(typeof(CountContext))]
    [Migration("20220705114455_DataSeed")]
    partial class DataSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("CounterAPI.Entities.Count", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Counts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            CountNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            CountNumber = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
